application: cloud-computing-twitter-buzz
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: a3.app

libraries:
- name: jinja2
  version: latest
- name: numpy
  version: "1.6.1"